steps:
  # 테스트
  - name: 'golang:1.22'
    entrypoint: 'go'
    args: ['test', './...']

  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go-board:$COMMIT_SHA'
      - '.'

  # 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/go-board:$COMMIT_SHA'

  # Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'go-board'
      - '--image=gcr.io/$PROJECT_ID/go-board:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'

images:
  - 'gcr.io/$PROJECT_ID/go-board:$COMMIT_SHA'
